### ISSUE TITLE
role keyword causes error

### ISSUE THREAD

**Issue by atul-tewari** [brantburnett/couchbase-index-manager#49]
We have been successfully creating indexes in Couchbase 5.5.2 using couchbase-index-manager, until we ran into this definition that contains, I presume, a keyword "role".  The definition of the index is:

`name: idx_xiplay_portalUser
index_key:
  - role
condition: (docType = 'PortalUser')`

The error is 
`
Error: Invalid index definition for idx_xiplay_portalUser: syntax error - at role
    at /Users/atultewari/projects/carnival/couchbase/node_modules/couchbase-index-manager/dist/index-definition.js:509:23
    at Generator.throw (<anonymous>)
    at step (/Users/atultewari/projects/carnival/couchbase/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/atultewari/projects/carnival/couchbase/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13`

Anything we can do to avoid this error.  If I change the attribute from "role" to something like "grouprole" it works fine.

Thanks!

**Comment by brantburnett** [comment]
@atul-tewari Try wrapping role in backticks, see what that does?

**Comment by atul-tewari** [comment]
Thanks for your prompt response.  The back ticks throw a different error:
```
YAMLException: bad indentation of a sequence entry at line 18, column 5:
      - `role`
        ^
    at generateError (/Users/xxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockSequence (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:962:7)
    at composeNode (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1358:12)
    at readBlockMapping (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at loadAll (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1583:19)
    at Object.safeLoadAll (/Users/xxxxxxx/projects/xxxxxxx/couchbase/node_modules/js-yaml/lib/js-yaml/loader.js:1610:5)
```

**Comment by atul-tewari** [comment]
Ah this worked:

```
name: idx_something_portalUser
index_key:
  - "`role`"
condition: (docType = 'PortalUser')
---
```

Thank you for providing that hint.
